// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbMReBR8775_bsa-ExQBwdj9aJCSNFek4',
    appId: '1:813685382162:web:1d503c82121e62d07a8ccb',
    messagingSenderId: '813685382162',
    projectId: 'shopatoz-3a77a',
    authDomain: 'shopatoz-3a77a.firebaseapp.com',
    storageBucket: 'shopatoz-3a77a.firebasestorage.app',
    measurementId: 'G-QTSD9NWB2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTKMmoIWyIJ7IRiREXtGqWP97J1TogL8U',
    appId: '1:813685382162:android:2c3c1ed767dfffea7a8ccb',
    messagingSenderId: '813685382162',
    projectId: 'shopatoz-3a77a',
    storageBucket: 'shopatoz-3a77a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD21wL_rFSMmgZNfOa5YyUFEEVJZXdCMPk',
    appId: '1:813685382162:ios:0a7832a4fd9894287a8ccb',
    messagingSenderId: '813685382162',
    projectId: 'shopatoz-3a77a',
    storageBucket: 'shopatoz-3a77a.firebasestorage.app',
    iosBundleId: 'com.example.shopAz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD21wL_rFSMmgZNfOa5YyUFEEVJZXdCMPk',
    appId: '1:813685382162:ios:0a7832a4fd9894287a8ccb',
    messagingSenderId: '813685382162',
    projectId: 'shopatoz-3a77a',
    storageBucket: 'shopatoz-3a77a.firebasestorage.app',
    iosBundleId: 'com.example.shopAz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbMReBR8775_bsa-ExQBwdj9aJCSNFek4',
    appId: '1:813685382162:web:7bf53fdb58c20ed67a8ccb',
    messagingSenderId: '813685382162',
    projectId: 'shopatoz-3a77a',
    authDomain: 'shopatoz-3a77a.firebaseapp.com',
    storageBucket: 'shopatoz-3a77a.firebasestorage.app',
    measurementId: 'G-MQKCDJZT6K',
  );
}
